### ISSUE TITLE
Unclear error when running the conf command (started 05/10/2022)

### ISSUE THREAD

**Issue by davidawad** [caleb531/open-conference-url#14]
Not sure what changed but for some reason the extension now breaks when trying to run it. It worked beautifully up until today (and I use it every day) so I'd love to help however I can here.

It seems like the code to fetch events is no longer able to get the array properly, not sure that the calendar application has updated it's interface or something. 

one other aside, for latest MacOS I'm using a builtin python install instead of the default because of the upgrade to python3. 
that's located on my machine at `/Library/Frameworks/Python.framework/Versions/2.7/bin/python` but I don't think that matters here.

I'm on application version 2.1.1 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/4019054/167703139-41ba63ce-d8c8-4870-9555-b0f7c7dd30fd.png">

Latest MacOS on M1 Max 14inch Macbook Pro
`Darwin sodium 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64` 

```
[14:57:04.055] Logging Started...
[14:57:07.774] Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469%3EAD06006F-71F6-4731-9942-D0697E95329A)] Queuing argument '(null)'
[14:57:07.837] Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469%3EAD06006F-71F6-4731-9942-D0697E95329A)] Script with argv '(null)' finished
[14:57:07.839] ERROR: Open Conference URL[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469%3EAD06006F-71F6-4731-9942-D0697E95329A)] Code 1: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/david/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469/ocu/list_events.py", line 115, in <module>
    main()
  File "/Users/david/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469/ocu/list_events.py", line 79, in main
    all_events = [event for event in get_events() if event.conference_url]
  File "/Users/david/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A10A40B6-BB43-4CE2-A92E-B4E688D58469/ocu/list_events.py", line 31, in get_events
    return [Event(event_blob) for event_blob in event_blobs]
  File "ocu/event.py", line 17, in __init__
    self.title = self.parse_title()
  File "ocu/event.py", line 30, in parse_title
    return re.search(r'^(.*?)\n', self.blob).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by davidawad** [comment]
Good news, I was so detailed in documenting this that I realized it's been updated from v2.1.1 to 4. 

This fixed both my previous python issue (thanks for upgrading to 3!)

This also fixed my issue with the events getting fetched. 

THANK YOU again to @caleb531 for building this extension.

**Comment by caleb531** [comment]
@davidawad Sure! I was _just_ going to recommend updating to the latest version of the workflow. There's been A LOT of improvement since v2.1.1. 😁

**Comment by davidawad** [comment]
awesome, hopefully if others find this they can just upgrade and they'll be sorted.
