### ISSUE TITLE
Can't fetch calendar entries

### ISSUE THREAD

**Issue by abhilesh** [caleb531/open-conference-url#2]
Hey, I'm running into this error where the workflow cannot fetch calendar entries. I did give the workflow permissions to access my calendar on the first run and have reinstalled it a few times.

Below is the debugging message when I type 'conf' in Alfred. Any help is appreciated.

[10:35:25.465] ERROR: Open Conference URL[Script Filter] Code 1: Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/abhilesh/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CDEC069C-F7DC-4FD3-814E-7FD12C99E074/ocu/list_events.py", line 10, in <module>
    from ocu.cache import cache
  File "ocu/cache.py", line 130, in <module>
    cache = Cache()
  File "ocu/cache.py", line 42, in __init__
    self.refresh()
  File "ocu/cache.py", line 110, in refresh
    if self.get('event_blobs') != event_blobs:
  File "ocu/cache.py", line 77, in get
    return self.__dict__[key]
KeyError: u'event_blobs'

**Comment by zalewskigrzegorz** [comment]
Hi I also got this:
`[00:11:13.000] ERROR: Open Conference URL[Script Filter] Code 1: Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/gzale/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0FDA3AA8-7D70-4BC1-85E0-D9D3490DEFB1/ocu/list_events.py", line 10, in <module>
    from ocu.cache import cache
  File "ocu/cache.py", line 130, in <module>
    cache = Cache()
  File "ocu/cache.py", line 42, in __init__
    self.refresh()
  File "ocu/cache.py", line 110, in refresh
    if self.get('event_blobs') != event_blobs:
  File "ocu/cache.py", line 77, in get
    return self.__dict__[key]
KeyError: u'event_blobs'`

**Comment by abhilesh** [comment]
I was able to solve this by making some modifications on my local copy of the source code, but I see a more recent commit on the code (5 days) that might have fixed the issue. Have you tried re-installing the latest version of the workflow?

If not, I can share the fixes I made on my local copy that made the code functional for me.
